name: CI

on:
  # å°æ–¼ main branch å»ºç«‹ Branch èˆ‡ Pull Request æ™‚è§¸ç™¼ workflow 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # å…è¨±ä½ å¾ Action é ç°½ä¸Šæ‰‹å‹•åŸ·è¡Œ workflow
  workflow_dispatch:

# Job å¯ä»¥å¾ªåºæˆ–å¹³è¡ŒåŸ·è¡Œ
jobs:
  build:
    runs-on: ubuntu-latest
    container: jhhlab/biovoltron-ci-env:20230914
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: build
      run: |
        mkdir build
        cd build
        cmake .. -DGCOV=ON
        make -j
    - name: test
      run: |
        cd build
        ./tests/biovoltron-test

    - name: deploy pages
      env:
        MY_SECRET  : ${{secrets.PAT_TOKEN}}
        USER_NAME  : githubaction
        USER_EMAIL : githubaction@fake.com
        PUBLISH_DIR: build/doc/doxygen/html
      run: |
        cd $PUBLISH_DIR
        git init
        git config --local user.name $USER_NAME
        git config --local user.email $USER_EMAIL
        git status
        git remote add origin https://$MY_SECRET@github.com/$GITHUB_REPOSITORY.git
        git checkout -b gh-pages
        git add --all
        git commit -m "deploy to Github pages"
        git push origin gh-pages -f
        echo ğŸ¤˜ deploy gh-pages complete.
